#!/usr/bin/env bash

## Envinronment and theme
BSPDIR="$HOME/.config/bspwm"

export PATH="${PATH}:$BSPDIR/scripts:$BSPDIR/themes/.current/scripts"

export XDG_CURRENT_DESKTOP='bspwm'
export EDITOR=nvim
export VISUAL=$EDITOR

export _JAVA_AWT_WM_NONREPARENTING=1

source "${BSPDIR}/themes/.current/theme.bash"

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

## Configuration
# Workspaces
monitor="$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)"
bspc monitor "$monitor" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

# Apply config
bspc config border_width "$bspwm_border"
bspc config window_gap "$bspwm_gap"
bspc config split_ratio "$bspwm_sratio"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

bspc config normal_border_color "$bspwm_normal_bc"
bspc config active_border_color "$bspwm_active_bc"
bspc config focused_border_color "$bspwm_focused_bc"
bspc config presel_feedback_color "$bspwm_presel_fc"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true
bspc config presel_feedback true

bspc wm --adopt-orphans

## Winrules

# remove all rules first
bspc rule -r *:*

# 1 - terminal
bspc rule -a kitty desktop='^1' follow=on focus=on

# 2 - web
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a chromium desktop='^2' follow=on focus=on

# 3 - files
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a qBittorrent desktop='^3' follow=on focus=on

# 4 - notes
bspc rule -a obsidian desktop='^4' follow=on focus=on

# 5 - media
declare -a media=(Audacity Gimp-2.1 Inkscape Lxmusic Music MPlayer mpv obs Spotify vlc)
for i in "${media[@]}"; do
  bspc rule -a "$i" desktop='^5' follow=on focus=on
done

# 6 - communication
declare -a comm=(discord Thunderbird TelegramDesktop Hexchat)
for i in "${comm[@]}"; do
  bspc rule -a "$i" desktop='^6' follow=on focus=on
done

# 7 - system
declare -a settings=(GParted VirtualBox Manager Lxappearance Lxtask Lxrandr Arandr Pavucontrol Exo-helper-1 Xfce4-power-manager-settings)
for i in "${settings[@]}"; do
  bspc rule -a "$i" desktop='^7' state=floating follow=on focus=on
done

# Always Float
declare -a floating=(kitty-float "Picture-in-Picture" "Firefox:Places" "Firefox:Biblioteca" *:*:"Picture-in-Picture"
  Viewnior Nm-connection-editor calamares Calamares)
for i in "${floating[@]}"; do
  bspc rule -a "$i" state=floating follow=on focus=on
done

bspc rule -a stalonetray state=floating manage=off

## Autostart

# Kill if already running
killall udiskie sxhkd dunst ksuperkey xfce4-power-manager bspc || true

# Lauch xsettingsd daemon
#xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
  /usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd &

# Auto-mount USB drives
udiskie &

# Power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr &

# XSettings daemon
killall -HUP xsettingsd
xsettingsd --config="$BSPDIR"/themes/.current/xsettingsd &

# Wallpaper
#wal -R
feh --no-fehbg --bg-fill "$BSPDIR/themes/.current/wallpaper" &
#nasa-wallpaper -a &

# Blue light filter
redshift -P -l -23.81:-45.37 -t 6500:4000 &

# Turn on keyboard leds
xset led 3 &

# Make Caps-Lock behave like esc when released and ctrl when pressed
#setxkbmap -option ctrl:nocaps &
#xcape -e 'Control_L=Escape' &

# Start bspwm scripts
#bspbar
#bspcomp
dunst -config "$BSPDIR"/themes/.current/dunstrc &
bspfloat &
