#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# bspwm directory
THEMEDIR="$HOME/.config/bspwm/themes/.current"

# Launch dunst daemon
if [[ $(pidof dunst) ]]; then
  pkill dunst
fi

dunst -config "$THEMEDIR"/dunstrc &
