#!/usr/bin/env bash

if [ "$1" == "--float" ]; then
	kitty --class 'kitty-float'
elif [ "$1" == "--full" ]; then
	kitty --class 'kitty-fullscreen' \
			  --start-as=fullscreen \
			  -o window_padding_width=30 \
			  -o background_opacity=0.95 -o font_size=20
else
	kitty ${@}
fi
