#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
RASI="$DIR/themes/.current/rofi/launcher.rasi"

# Run
rofi \
  -show drun \
  -kb-cancel Alt-F1,Escape \
  -theme ${RASI}
